# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  NODE_VERSION: '12.x'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    
    # Setup the version of Node.js to use as part of the job
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    # Install the vsce npm package
    - name: Install the vsce npm package
      run: |
        npm install
        npm install -g vsce

    # Run the vsce commands that will package and publish the extension pack
    - name: Package the extension pack
      run: |
        vsce package
        vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
